[project]
name = "ctp"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "Jean-Brice GACHOT", email = "jbgachot@gmail.com" }]
dependencies = []
requires-python = ">=3.14"
readme = "README.md"
license = { text = "AGPL-3.0-only" }

[dependency-groups]
dev = ["ruff>=0.9.2", "mpremote>=1.24.1"]

[tool.ruff]
exclude = [".venv"]
line-length = 100
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/linter
select = ["E", "F", "UP", "B", "SIM", "I"]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
lint = "ruff check --fix"
format = "ruff format"
